"""add generation column

Revision ID: b288f813060e
Revises: f91c33100cd6
Create Date: 2026-03-15 23:43:23.806419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b288f813060e'
down_revision: Union[str, Sequence[str], None] = 'f91c33100cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('height', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hp', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attack', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('defense', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('special_attack', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('special_defense', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('speed', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
