"""add image_path column to pokemon

Revision ID: e584935fff32
Revises: 362e12e84cec
Create Date: 2026-03-18 20:51:39.763295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e584935fff32'
down_revision: Union[str, Sequence[str], None] = '362e12e84cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('height', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hp', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attack', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('defense', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('special_attack', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('special_defense', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('speed', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('types', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('abilities', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('generation', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('region', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
